backend:
  name: github
  repo: zizelle690-hub/Witholi
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: blog
    label: Blog Posts
    folder: src/content/blog
    create: true
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: pubDate, widget: datetime }
      - { label: Description, name: description, widget: string }
      - { label: Category, name: category, widget: select, options: ["Sexual & Reproductive Health", "Hormones", "Fertility", "Chronic Disease", "Preventive Lifestyle"] }
      - { label: Body, name: body, widget: markdown }